export { default as Estudios} from './Estudios'
export { default as Experiencia} from './Experiencia'
export { default as Habilidades} from './Habilidades'
export { default as Perfil} from './Perfil'
export {default as Principal} from './Principal'